clc, clear

load('paths')
load([inriaDataSet '/inriaPosTrain'])

windowSize = [134 70];
method(1) = methodStruct( ...
    'window',{'type','square','scales',2^(1/3).^(0:6),'spacing',10,'windowSize',windowSize}, ...
    'cellhist',{...
    'colour','gray',...
    'contentType','go',...
    'magnitudeType','m',...
    'rescale',1,...
    'scaleBase',2^(1/3),...
    'scaleOffset',0,...
    'gridType','square window',...
    'gridSize',2.5,...
    'gridRadius',windowSize,...
    'centerFilter','none',...
    'cellFilter','gaussian',...
    'cellSigma',[1 1],...
    'normType','pixel',...
    'normSigma',[1.6 1.6],...
    'binSigma',1,...
    'binCount',12,...
    'cellNormStrategy',4},...
    true,{'co-'});
method(2) = methodStruct( ...
    'window',{'type','square','scales',1,'spacing',50,'windowSize',windowSize}, ...
    'hog',{'variant','dalaltriggs'}, ...
    0,{'rx-'});
mFunc1 = parseMethod(method(1));
mFunc2 = parseMethod(method(2));

D1 = inriaDescriptors(images(1),mFunc1);
D2 = inriaDescriptors(images(1),mFunc2);

figure,plot(D1),figure,plot(D2)