clc, clear all

% method = methodStruct( ...
%     '',{}, ...
%     'full-hog',{}, ...
%     0,{'rx-'});

svmArgs = '-h 0';

gridRadius = 3;
method = methodStruct( ...
    'grid',{'type','square','scales',1,'gridRadius',gridRadius}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'rescale',1,...
   'gridType','polar central',...
   'gridSize',[1 0],...
   'gridRadius',gridRadius,...
   'centerFilter','none',...
   'cellFilter','gaussian',...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[1.6 1.6],...
   'binSigma',1.2,...
   'binCount',12,...
   'cellNormStrategy',4},...
   0,{'co-'});

totalTime = tic;
[Lsvm, acc, P] = inriaTest(6,1,method,svmArgs);
totalTime = toc(totalTime)