clc, clear all

windowSize = [134 70];

% SVM arguments
% -c cost of C-SVC (default 1)
% -p epsilon (default 0.1)
svmArgs = '-s 1 -c 0.01 -p 0.1';

% method = methodStruct( ...
%      '',{}, ...
%      'full-hog',{}, ...
%      0,{'rx
method = methodStruct( ...
     'window',{'type','square','scales',2^(1/3).^(0:6),'spacing',10,'windowSize',windowSize}, ...
     'hog',{}, ...
     0,{'rx-'});

% method = methodStruct( ...
%   'window',{'type','square','scales',1,'spacing',10,'windowSize',windowSize}, ...
%   'cellhist',{...
%   'colour','gray',...
%   'contentType','go',...
%   'magnitudeType','m',...
%   'rescale',1,...
%   'scaleBase',2^(1/3),...
%   'scaleOffset',0,...
%   'gridType','square window',...
%   'gridSize',3,...
%   'gridRadius',windowSize,...
%   'centerFilter','none',...
%   'cellFilter','gaussian',...
%   'cellSigma',[1 1],...
%   'normType','pixel',...
%   'normSigma',[1.6 1.6],...
%   'binSigma',1.2,...
%   'binCount',12,...
%   'cellNormStrategy',4},...
%   0,{'co-'});

profile off,profile on
totalTime = tic;
% svmPath = inriaValidateSvm(6,1,method,svmArgs,true);
svmPath = inriaTestSvm(method,svmArgs,true);
% [ROCAUC,knnPath] = inriaTestKnn(6,1,method,true,30);
totalTime = toc(totalTime)
profile off
% profile viewer

plotInriaResults(svmPath)