clc, clear all

 method = methodStruct( ...
     '',{}, ...
     'full-hog',{'variant','DalalTriggs'}, ...
     0,{'rx-'});

svmArgs = '-h 0 -t 0';

gridRadius = 3;
%method = methodStruct( ...
%    'grid',{'type','square','scales',1,'gridRadius',gridRadius}, ...
%   'cellhist',{...
%   'colour','gray',...
%   'contentType','go',...
%   'magnitudeType','m',...
%   'rescale',1,...
%   'gridType','polar central',...
%   'gridSize',[1 0],...
%   'gridRadius',gridRadius,...
%   'centerFilter','none',...
%   'cellFilter','gaussian',...
%   'cellSigma',[1 1],...
%   'normType','pixel',...
%   'normSigma',[1.6 1.6],...
%   'binSigma',1.2,...
%   'binCount',12,...
%   'cellNormStrategy',4},...
%   0,{'co-'});

%method = methodStruct( ...
%    'grid',{'type','square','scales',1,'gridRadius',gridRadius}, ...
%   'cellhist',{...
%   'colour','gray',...
%   'contentType','si',...
%   'magnitudeType','c',...
%   'rescale',1,...
%   'gridType','polar central',...
%   'gridSize',[1 0],...
%   'gridRadius',gridRadius,...
%   'centerFilter','none',...
%   'cellFilter','gaussian',...
%   'cellSigma',[1 1],...
%   'normType','pixel',...
%   'normSigma',[1.6 1.6],...
%   'binSigma',2,...
%   'binCount',8,...
%   'cellNormStrategy',4},...
%   0,{'co-'});

totalTime = tic;
[Lsvm, acc, P, svmPath] = inriaTest(6,[],method,svmArgs,true);
totalTime = toc(totalTime)
