% clc, clear

load('paths')

I = imread([inriaDataSet '/Train/neg/D2004-05-16_11h37m38s.jpg']);
I = im2single(I);
windowSize = [134 70];
scaleBase = 2^(1/3);
scales = scaleBase .^ (0:log(min([size(I,1) size(I,2)] ./ windowSize))/log(scaleBase));
% scales = scales(1);

method = methodStruct( ...
  'window',{'type','square','scales',scales,'spacing',6,'windowSize',windowSize}, ...
  'cellhist',{...
  'colour','gray',...
  'contentType','go',...
  'magnitudeType','m',...
  'rescale',1,...
  'scaleBase',scaleBase,...
  'scaleOffset',0,...
  'gridType','square window',...
  'gridSize',3,...
  'gridRadius',windowSize,...
  'centerFilter','none',...
  'cellFilter','gaussian',...
  'cellSigma',[1 1],...
  'normType','pixel',...
  'normSigma',[1.6 1.6],...
  'binSigma',1.2,...
  'binCount',12,...
  'cellNormStrategy',4},...
  0,{'co-'});

[mFunc, mName] = parseMethod(method);
[X,D] = mFunc(I,'','',false);