clc, clear all

% peakThresholdDog = 4.5;
% peakThresholdDogFull = 5;
% peakThresholdHarris = 10^4;
%     'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
% method = methodStruct( ...
%    'constant',{'F',[440 451 4],'cache',0}, ...
%    'cellhist',{...
%    'colour','gray',...
%    'contentType','go',...
%    'magnitudeType','m',...
%    'rescale',1,...
%    'gridType','concentric polar central',...
%    'gridSize',[8 2],...
%    'gridRadius',10,...
%    'centerFilter','gaussian',...
%    'centerSigma',[1.3 1.3],...
%    'cellFilter','polar gaussian',...
%    'cellSigma',[1 1],...
%    'normType','pixel',...
%    'normSigma',[2 2],...
%    'binSigma',1.2,...
%    'binCount',8,...
%    'cellNormStrategy',0,...
%    'cache',0},...
%    0,{'co-'});
% 
% params = load('results/optimize/parameterStudyGo_1-of-6.mat');
% method = modifyDescriptor(params.method,'centerSigma',[1.6 1.6],'rescale',2);
% method.detector = 'constant';
% method.detectorArgs = {'F',[445 451 2.8],'cache',0};
% desArgs = struct(method.descriptorArgs{:});
% 
% [mFunc, mName] = parseMethod(method);
% 
% I = imread('../defence/img/shoeOriginal.jpg');
% I = im2single(I);
% 
% [X,D] = mFunc(I,'','',false);

load('cellHistExampleDefence')

fig('unit','inches','width',6,'height',6,'fontsize',8);
visualizeCellHistDefence({L.none},P,H,cells,binC,gridRadius,'go')
path = '../defence/img/shoeDescriptorZoom.pdf';
saveTightFigure(gcf,path)

Irgb = imread('../defence/img/shoeOriginal.jpg');
figure
imshow(Irgb)
hold on
plot(F(:,1),F(:,2),'c.')
drawCircle(F(:,1),F(:,2),gridRadius/rescale*F(:,3),'c')
path = '../defence/img/shoeDescriptor.pdf';
saveTightFigure(gcf,path)

% visualizeCellHist({L.none},P(n,:),H(:,:,n),cells,binC,2,'go')