clc, clear all

setNum = 1;
imNum = 57;
liNum = 0;

peakThresholdDog = 6.5;
peakThresholdDogFull = 5;
peakThresholdHarris = 10^4;

method = methodStruct( ...
   'debug',{'cache',0},...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'rescale',1/2,...
   'gridType','polar central',...
   'gridSize',[8 2],...
   'gridRadius',10,...
   'centerFilter','none',...
   'centerSigma',1*[1 1],...
   'cellFilter','polar gaussian',...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',2.5,...
   'binCount',8,...
   'cellNormStrategy',0,...
   'cache',0},...
   0,{'co-'});

[mFunc, mName] = parseMethod(method);
tic
profile off, profile on

load('paths');
I = rand(495,500,3);
imName = 'test';
[X,D] = mFunc(I,dtuResults,imName,false);
D = reshape(D(1,:),8,17);
sum(D,1)
figure
subplot(1,2,1)
imshow(D,[])

profile off
toc
% profile viewer