clc, clear all

setNum = 1;
imNum = 57;
liNum = 0;

peakThresholdDog = 6.5;
peakThresholdDogFull = 5;
peakThresholdHarris = 10^4;

method = methodStruct( ...
    'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'rescale',1/2,...
   'gridType','polar central',...
   'gridSize',[8 3],...
   'gridRadius',10,...
   'centerFilter','gaussian',...
   'centerSigma',[1 1],...
   'cellFilter','gaussian',...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',1.15,...
   'binCount',8,...
   'cellNormStrategy',0,...
   'cache',0},...
   0,{'co-'});

[mFunc, mName] = parseMethod(method);
% profile off, profile on
tic

[X,D] = dtuFeatures(setNum, imNum, liNum, mFunc, 1);

% load('paths');
% I = rand(495,500,3);
% imName = 'test';
% [X,D] = mFunc(I,dtuResults,imName,false);
D = reshape(D(1,:),8,25);
sum(D,1)
% figure
% subplot(1,2,1)
% imshow(D,[])

toc
% profile off
% profile viewer