clc, clear all

setNum = 1;
imNum = 57;
liNum = 0;

peakThresholdDog = 6.5;
peakThresholdDogFull = 5;
peakThresholdHarris = 10^4;

method = methodStruct( ...
    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
    'cellhist',{...
    'colour','gray',...
    'contentType','go',...
    'magnitudeType','m',...
    'scaleBase',2,...
    'rescale',1,...
    'gridType','concentric polar',...
    'gridSize',[8 2],...
    'gridRadius',17,...
    'centerSigma',[Inf Inf],...
    'cellSigma',[1 1],...
    'normType','pixel',...
    'normSigma',[2 2],...
    'binSigma',[2.5],...
    'binCount',[8],...
    'cache',0},...
    0,{'co-'});

[mFunc, mName] = parseMethod(method);
tic
profile off, profile on
[X,D] = dtuFeatures(setNum,imNum,liNum,mFunc);
profile off
toc
profile viewer