function [minima, maxima] = findExtrema(A)

r = size(A,1);
c = size(A,2);

x_zeros = zeros(1,c);
y_zeros = zeros(r,1);

r_sign = sign(A(:,2:end) - A(:,1:end-1));
d_sign = sign(A(2:end,:) - A(1:end-1,:));
rd_sign = sign(A(2:end,2:end) - A(1:end-1,1:end-1));
ru_sign = sign(A(1:end-1,2:end) - A(2:end,1:end-1));

minima = [x_zeros; d_sign == -1] & [d_sign == 1; x_zeros] & ...
         [y_zeros, r_sign == -1] & [r_sign == 1, y_zeros] & ...
         [zeros(1,c); zeros(r-1,1), rd_sign == -1] & ...
         [rd_sign == 1, zeros(r-1,1); zeros(1,c)] & ...
         [zeros(r-1,1), ru_sign == -1; zeros(1,c)] & ...
         [zeros(1,c); ru_sign == 1, zeros(r-1,1)];
maxima = [x_zeros; d_sign == 1] & [d_sign == -1; x_zeros] & ...
         [y_zeros, r_sign == 1] & [r_sign == -1, y_zeros] & ...
         [zeros(1,c); zeros(r-1,1), rd_sign == 1] & ...
         [rd_sign == -1, zeros(r-1,1); zeros(1,c)] & ...
         [zeros(r-1,1), ru_sign == 1; zeros(1,c)] & ...
         [zeros(1,c); ru_sign == -1, zeros(r-1,1)];

end