clc, clear all

setNum = 1:60;
peakThresholdDog = 6.5;
peakThresholdHarris = 10^4;

method = struct('detector',{},'detectorArgs',{},'descriptor',{},...
    'descriptorArgs',{},'cache',{},'plotParams',{});
colour = 'gray';

method(1) = methodStruct( ...
    'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','si',...
   'magnitudeType','c',...
   'rescale',1/2,...
   'gridType','concentric polar',...
   'gridSize',[12 2],...
   'gridRadius',11.5,...
   'centerFilter','gaussian',...
   'centerSigma',[1.5 1.5],...
   'cellFilter','polar gaussian',...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',1.2,...
   'binCount',9,...
   'cellNormStrategy',0,...
   'binStrategy',0},...
   0,{'co-'});

method(2) = modifyDescriptor(method(1),'binStrategy',1);

totalTime = tic;
[ROC,PR] = dtuTest(setNum,method,1:6,false,true,'train')
totalTime = toc(totalTime)

[meanROC, stdROC] = computeMeanAuc(ROC,numel(setNum),numel(method))
[meanPR, stdPR] = computeMeanAuc(PR,numel(setNum),numel(method))

save('dtuTestBinStrategySi.mat')