clc, clear all

setNum = 1:60;
peakThresholdDog = 6.5;
peakThresholdHarris = 10^4;

method = struct('detector',{},'detectorArgs',{},'descriptor',{},...
    'descriptorArgs',{},'cache',{},'plotParams',{});
colour = 'gray';
matchCache = 1;

method(1) = methodStruct( ...
   'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'scaleBase',2^(1/3),...
   'rescale',1/2,...
   'gridType','concentric polar',...
   'gridSize',[8 2],...
   'gridRadius',10,...
   'centerFilter','gaussian',...
   'centerSigma',[1.5 1.5],...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',2.5,...
   'binCount',8,...
   'cellNormStrategy',0,...
   'cache',1},...
   1,{'ro-'});

method(end+1) = modifyDescriptor(method(1),'cellNormStrategy',1);
method(end).plotParams = {'go-'};

method(end+1) = modifyDescriptor(method(1),'cellNormStrategy',2);
method(end).plotParams = {'bo-'};

method(end+1) = modifyDescriptor(method(1),'cellNormStrategy',3);
method(end).plotParams = {'mo-'};

totalTime = tic;
[ROC,PR] = dtuTest(setNum,method,1:6,true,false,'train')
totalTime = toc(totalTime)

[meanROC, stdROC] = computeMeanAuc(ROC,numel(setNum),numel(method))
[meanPR, stdPR] = computeMeanAuc(PR,numel(setNum),numel(method))

load('paths')
save([dtuResults '/resultsCellNormStrategy.mat'])