clc, clear all

setNum = dtuSplitSets(10,1);
peakThresholdDog = 6.5;
peakThresholdHarris = 10^4;

method = struct('detector',{},'detectorArgs',{},'descriptor',{},...
    'descriptorArgs',{},'cache',{},'plotParams',{});
colour = 'gray';
matchCache = 1;

method(1) = methodStruct( ...
   'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'scaleBase',2^(1/3),...
   'rescale',1/2,...
   'gridType','concentric polar',...
   'gridSize',[8 2],...
   'gridRadius',10,...
   'centerFilter','box',...
   'centerSigma',[Inf Inf],...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',2.5,...
   'binCount',8,...
   'cellNormStrategy',1,...
   'cache',0},...
   0,{'ro-'});

totalTime = tic;
[ROC,PR] = dtuTest(setNum,method,1:6,false,true,'train')
totalTime = toc(totalTime)

[meanROC, stdROC] = computeMeanAuc(ROC,numel(setNum),numel(method))
[meanPR, stdPR] = computeMeanAuc(PR,numel(setNum),numel(method))

load('paths')
save([dtuResults '/resultsScaleBase04.mat'])
