clc, clear all;

setNum = 1;
imNum = [25];

LEDpos = [180 30;...
          180 50;...
          133  0;...
          133 20;...
          133 40;...
          133 60;...
          133 80;...
           89  1;...
           89 17;...
           89 33;...
           89 49;...
           89 65;...
           89 81;...
           39  0;...
           39 20;...
           39 40;...
           39 60;...
           39 80;...
            0  1];

liPathPos = [linspace(188,-7,10)',ones(10,1)*40;...
         ones(10,1)*90,linspace(-25,105,10)'];

liNum = 1:19;
liPathInds.x = 1:10;
liPathInds.z = 11:20;

imSize = size(imread(dtuImagePath(setNum(1),imNum(1),liNum(1))));

for s = setNum
    disp(['Set ' num2str(s) '/' num2str(numel(setNum))]);
    for i = imNum
        disp(['Image: ' num2str(i)]);

        % Load all light images for this position/imNum
        Ilight = zeros([imSize numel(liNum)]);
        for l = 1:liNum
            Ilight(:,:,:,l) = imread(dtuImagePath(s,i,l,'raw'));
        end

        fieldnames(liPathInds)'
        for t = fieldnames(liPathInds)'
            inds = liPathInds.(char(t));
            for p = 1:numel(inds)
                savePath = dtuImagePath(s,i,p,char(t));
            end
        end
    end
end
