clc, clear all

setNum = 1;
setNum = dtuSplitSets(10,2);
peakThresholdDog = 6.5;
peakThresholdHarris = 10^4;

method = struct('detector',{},'detectorArgs',{},'descriptor',{},...
    'descriptorArgs',{},'cache',{},'plotParams',{});
colour = 'gray';
matchCache = 1;

% method(end+1) = methodStruct( ...
%      'vl',{'method','DoG','peakthreshold',peakThresholdDog}, ...
%      'sift',{'colour',colour}, ...
%      matchCache, {'bx-'});
%method(end+1) = methodStruct( ...
%    '',{'cache',0}, ...
%    'full-sift',{'colour',colour,'PeakThresh',peakThresholdDog,'cache',1}, ...
%    matchCache,{'rx-'});

method(end+1) = methodStruct( ...
   'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'scaleBase',2^(1/3),...
   'rescale',1/2,...
   'gridType','concentric polar',...
   'gridSize',[8 2],...
   'gridRadius',10,...
   'centerSigma',[Inf Inf],...
   'cellSigma',[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',2.5,...
   'binCount',8,...
   'cache',1},...
   matchCache,{'co-'});

totalTime = tic;
[ROC,PR] = dtuTest(setNum,method,1:6,false,true,'train');
totalTime = toc(totalTime)
