clc, clear all

setNum = 1;
peakThresholdDog = 5;
peakThresholdHarris = 10^4;

method = struct('detector',{},'detectorArgs',{},'descriptor',{},'descriptorArgs',{},'plotParams',{});
colour = 'gray';
%method(end+1) = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'cellhist',{'colour','opponent','contentType','go', ...
%   'gridType','polar','gridSize',[8 2],'gridSpacing',3, ...
%   'cellSigma',[1.5 1.5],'binSigma',1/2,'binCount',8},{'ro-'});
%method(end+1) = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'cellhist',{'colour','opponent','contentType','si', ...
%   'gridType','polar','gridSize',[8 2],'gridSpacing',3, ...
%   'cellSigma',[1.5 1.5],'binSigma',1/2,'binCount',8},{'go-'});
%method(end+1) = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'cellhist',{'colour','opponent','contentType','go,si', ...
%   'gridType','polar','gridSize',[8 2],'gridSpacing',3, ...
%   'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[8 8]},{'mo-'});
%method(end+1) = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'cellhist',{'colour','opponent','contentType','go-si', ...
%   'gridType','polar','gridSize',[8 2],'gridSpacing',3, ...
%   'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'ko-'});
method(end+1) = methodStruct( ...
    'vl',{'method','DoG','peakthreshold',peakThresholdDog}, ...
    'sift',{'colour',colour},{'bx-'});
method(end+1) = methodStruct( ...
    '',{'cache',1}, ...
    'full-sift',{'colour',colour,'PeakThresh',peakThresholdDog,'cache',1},{'rx-'});

method(end+1) = methodStruct( ...
    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
    'cellhist',{...
    'colour','gray',...
    'contentType','go',...
    'magnitudeType','m',...
    'scaleBase',2^(1/3),...
    'rescale',1,...
    'gridType','concentric polar',...
    'gridSize',[8 2],...
    'gridRadius',17,...
    'centerSigma',[Inf Inf],...
    'cellSigma',[1 1],...
    'normType','pixel',...
    'normSigma',[2 2],...
    'binSigma',[2.5],...
    'binCount',[8],...
    'cache',1},...
    {'co-'});

% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'sift',{'colour','gray'},{'rx-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
%    'sift',{'colour','gray'},{'bx-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'contentType','go', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',pi/6,'binCount',8},{'mo-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
%    'cellhist',{'contentType','go', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',pi/6,'binCount',8},{'co-'});

% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','gray','contentType','go,si', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'ro-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','rgb bin','contentType','go,si', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'go-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','rgb','contentType','go,si', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'bo-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','opponent','contentType','go,si', ...
%    'gridType','polar','gridSize',[8 2],'gridSpacing',3, ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[8 8]},{'co-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','gaussian opponent','contentType','go,si', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'yo-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','c-colour','contentType','go,si', ...
%    'gridType','polar','gridSize',[8 2],'gridSpacing',3, ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[8 8]},{'mo-'});
% method(end+1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','perceptual','contentType','go,si', ...
%    'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%    'cellSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'ko-'});

dtuTest(setNum,method,[1:4]);
