clc, clear all

setNum = 1:6;
peakThresholdDog = 10;
peakThresholdHarris = 2*10^5;

colour = 'gray';
method(1) = methodStruct( ...
   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
   'cellhist',{'colour','opponent','contentType','go', ...
   'blockType','polar','blockSize',[8 2],'blockSpacing',3, ...
   'spatialSigma',[1.5 1.5],'binSigma',1/2,'binCount',8},{'ro-'});
method(2) = methodStruct( ...
   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
   'cellhist',{'colour','opponent','contentType','si', ...
   'blockType','polar','blockSize',[8 2],'blockSpacing',3, ...
   'spatialSigma',[1.5 1.5],'binSigma',1/2,'binCount',8},{'go-'});
method(3) = methodStruct( ...
   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
   'cellhist',{'colour','opponent','contentType','go,si', ...
   'blockType','polar','blockSize',[8 2],'blockSpacing',3, ...
   'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[8 8]},{'mo-'});
method(4) = methodStruct( ...
   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
   'cellhist',{'colour','opponent','contentType','go-si', ...
   'blockType','polar','blockSize',[8 2],'blockSpacing',3, ...
   'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'ko-'});
method(5) = methodStruct( ...
   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
   'sift',{'colour','opponent'},{'bx-'});

% method(1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'sift',{'colour','gray'},{'rx-'});
% method(2) = methodStruct( ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
%    'sift',{'colour','gray'},{'bx-'});
% method(3) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'contentType','go', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',pi/6,'binCount',8},{'mo-'});
% method(4) = methodStruct( ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
%    'cellhist',{'contentType','go', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',pi/6,'binCount',8},{'co-'});

% method(1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','gray','contentType','go,si', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'ro-'});
% method(2) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','rgb bin','contentType','go,si', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'go-'});
% method(3) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','rgb','contentType','go,si', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'bo-'});
% method(1) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','opponent','contentType','go,si', ...
%    'blockType','polar','blockSize',[8 2],'blockSpacing',3, ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[8 8]},{'co-'});
% method(5) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','gaussian opponent','contentType','go,si', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'yo-'});
% method(2) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','c-colour','contentType','go,si', ...
%    'blockType','polar','blockSize',[8 2],'blockSpacing',3, ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[8 8]},{'mo-'});
% method(7) = methodStruct( ...
%    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'cellhist',{'colour','perceptual','contentType','go,si', ...
%    'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%    'spatialSigma',[1.5 1.5],'binSigma',[1/2 1/2],'binCount',[4 4]},{'ko-'});

dtuTest(setNum,method);