clc, clear all

setNum = 4;
imNum = 49;
liNum = 0;

peakThresholdDog = 6.5;
peakThresholdHarris = 10^4;
matchCache = 0;
desSave = 1;

%     'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
method = methodStruct( ...
    'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',1}, ...
   'cellhist',{...
   'colour','gray',...
   'contentType','go',...
   'magnitudeType','m',...
   'rescale',1/2,...
   'gridType','log-polar',...
   'gridSize',[8 2],...
   'gridRadius',10,...
   'centerFilter','gaussian',...
   'centerSigma',5/3*[1 1],...
   'cellFilter','gaussian',...
   'cellSigma',1.05*[1 1],...
   'normType','pixel',...
   'normSigma',[2 2],...
   'binSigma',0.85,...
   'binCount',8,...
   'cellNormStrategy',0,...
   'cache',0},...
   matchCache,{'co-'});
% method = methodStruct( ...
%     '',{'cache',1},...
%     'full-sift',{'PeakThresh',peakThresholdDog,'cache',1},...
%     0,{'co-'});
% method = methodStruct( ...
%     'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',0},...
%     'sift',{'cache',0},...
%     matchCache,{'co-'});

% method = methodStruct( ...
%     'vl',{'method','dog','peakthreshold',peakThresholdDog,'cache',0},...
%     'none',{'cache',0},...
%     1,{'co-'});

t = 0.9;

[mFunc, mName] = parseMethod(method);
tic
profile on
match = imageCorrespondence(setNum,imNum,liNum,{mFunc},{mName},...
    method.cache,desSave);
profile off
toc
% profile viewer
plotAnalyseMatches(match(1),t,mName);
