clc, clear all

setNum = 1;
imNum = 57;
liNum = 0;

peakThresholdDog = 5;
peakThresholdDogFull = 5;
peakThresholdHarris = 10^4;
matchCache = 1;

%method = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'sift',{'colour','rgb'},{'go-'});

%     'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%     'cvtmser',{'ThresholdDelta',3,'cache',1},...
method = methodStruct( ...
    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
    'cellhist',{...
    'colour','gray',...
    'contentType','go',...
    'magnitudeType','m',...
    'scaleBase',2^(1/3),...
    'rescale',1,...
    'gridType','concentric polar',...
    'gridSize',[8 2],...
    'gridRadius',17,...
    'centerSigma',[Inf Inf],...
    'cellSigma',[1 1],...
    'normType','pixel',...
    'normSigma',[2 2],...
    'binSigma',[2.5],...
    'binCount',[8],...
    'cache',1},...
    1,...
    {'co-'});
% method = methodStruct( ...
%     '',{'cache',1},...
%     'full-sift',{'PeakThresh',peakThresholdDogFull,'cache',1},...
%     {'co-'});
% method = methodStruct( ...
%     'vl',{'method','dog','peakthreshold',peakThresholdDog},...
%     'sift',{'cache',1},...
%     {'co-'});
%method = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'cellhist',{'contentType','go','scaleBase',2, ...
%   'gridType','square','gridSize',[4 4],'gridSpacing',[3 3], ...
%   'cellSigma',[1.5 1.5],'binSigma',1/2,'binCount',8,'cache',1}, ...
%   {'co-'});

% method = methodStruct( ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
%    'k-jet',{'k',5,'sigma',10.6,'domain','auto'},{'co-'});

% method = methodStruct( ...
%    'dog',{'sigma',10.6,'k',2,'threshold',0.01}, ...
%    'k-jet',{'k',5,'sigma',10.6,'domain','auto'},{'co-'});

t = 0.9;

[mFunc, mName] = parseMethod(method);
tic
profile on
match = imageCorrespondence(setNum,imNum,liNum,mFunc,mName,matchCache);
profile off
toc
% profile viewer
plotAnalyseMatches(match,t,mName);
