clc, clear all

setNum = 1;
imNum = 12;
liNum = 'diffuse';

peakThresholdDog = 5;
peakThresholdHarris = 5*10^4;

%method = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'sift',{'colour','rgb'},{'go-'});
 method = methodStruct( ...
    'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
    'cellhist',{'colour','gray','contentType','go','scaleBase',2,'rescale',true,...
    'blockType','square','blockSize',[4 4],'blockSpacing',[2 2], ...
    'spatialSigma',[2.5 2.5],'binSigma',[1/2],'binCount',[8],'cache',1},{'co-'});
%method = methodStruct( ...
%   'vl',{'method','MultiscaleHarris','peakthreshold',peakThresholdHarris}, ...
%   'cellhist',{'contentType','go','scaleBase',2, ...
%   'blockType','square','blockSize',[4 4],'blockSpacing',[3 3], ...
%   'spatialSigma',[1.5 1.5],'binSigma',1/2,'binCount',8,'cache',1}, ...
%   {'co-'});
matchCache = 1;

% method = methodStruct( ...
%    'vl',{'method','dog','peakthreshold',peakThresholdDog}, ...
%    'k-jet',{'k',5,'sigma',10.6,'domain','auto'},{'co-'});

% method = methodStruct( ...
%    'dog',{'sigma',10.6,'k',2,'threshold',0.01}, ...
%    'k-jet',{'k',5,'sigma',10.6,'domain','auto'},{'co-'});

t = 0.9;

[mFunc, mName] = parseMethod(method);
tic
profile on
match = imageCorrespondence(setNum,imNum,liNum,mFunc,mName,matchCache);
profile off
% profile viewer
plotAnalyseMatches(match,t,mName);
